steps:
  - name: 'python:3.9'
    entrypoint: 'bash'
    args:
      - '-c'
      - 'pip install -r requirements.txt && python -m unittest discover -s .'
  - name: 'gcr.io/cloud-builders/docker'
    args:
      - build
      - '-t'
      - 'europe-docker.pkg.dev/$PROJECT_ID/financial-life-model/financial-life-model-image:latest'
      - '.'
    env:
      - PROJECT_ID=$PROJECT_ID
  - name: 'gcr.io/cloud-builders/docker'
    args:
      - push
      - 'europe-docker.pkg.dev/$PROJECT_ID/financial-life-model/financial-life-model-image:latest'
    env:
      - PROJECT_ID=$PROJECT_ID
  - name: 'gcr.io/cloud-builders/gcloud'
    args:
      - run
      - jobs
      - deploy
      - financial-life-model-job
      - --image=europe-docker.pkg.dev/$PROJECT_ID/financial-life-model/financial-life-model-image:latest
      - --region=europe-west1
      - --cpu=2
      - --memory=2Gi
      - --max-retries=0
      - --set-env-vars=PROJECT_ID=$PROJECT_ID